---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-init-creds
data:
  kc_admin_username: "admin"
  kc_admin_password: "admin"
  kc_init_realm_name: "flame"
  kc_init_clients: |
    service1:9dd01665c2f3f02f93c32d03bd854569f03cd62f439ccf9f0861c141b9d6330e
    service2:40e4abf259cffe49527ed7cbaca3c9c4ed4f77cc100372789d6679969802b4fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak-service
          image: quay.io/keycloak/keycloak:23.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-kc-srv
          env:
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: kc_admin_username
                  name: keycloak-init-creds
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: kc_admin_password
                  name: keycloak-init-creds
            - name: KC_PROXY
              value: "edge"
          args: ["start-dev"]
        - name: keycloak-sidecar
          image: quay.io/keycloak/keycloak:23.0.4
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: kc_admin_username
                  name: keycloak-init-creds
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: kc_admin_password
                  name: keycloak-init-creds
            - name: KEYCLOAK_INIT_REALM
              valueFrom:
                configMapKeyRef:
                  key: kc_init_realm_name
                  name: keycloak-init-creds
          volumeMounts:
            - mountPath: "/cfg"
              name: client-config
              readOnly: true
          command:
            - /bin/sh
            - -c
            - |
              export PATH="$PATH:/opt/keycloak/bin"
              echo "Waiting for Keycloak to be ready";
              until kcadm.sh config credentials --server http://keycloak-service:8080 --realm master --user "$KEYCLOAK_ADMIN" --password "$KEYCLOAK_ADMIN_PASSWORD";
              do
                sleep 5;
              done;
              echo "Initializing realm $KEYCLOAK_INIT_REALM if it doesn't exist yet";
              kcadm.sh create realms -s realm="$KEYCLOAK_INIT_REALM" -s enabled=true;
              while IFS="" read -r line || [ -n "$line" ];
              do
                IFS=: read client_id client_secret <<< "$line";
                echo "Creating client $client_id";
                kcadm.sh create clients -r "$KEYCLOAK_INIT_REALM" -s enabled=true -s clientId="$client_id" -s secret="$client_secret" -s directAccessGrantsEnabled=true -s serviceAccountsEnabled=true;
              done < /cfg/kc_init_clients;
              echo "Done, sleeping forever...";
              while true; do sleep 10000; done
      volumes:
        - name: client-config
          configMap:
            name: keycloak-init-creds
            items:
              - key: "kc_init_clients"
                path: "kc_init_clients"
